apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  PORT: "{{ .Values.service.server.port }}"
  MONGO_URI: "{{ .Values.config.mongoUri }}"
  REDIS_URL: "{{ .Values.config.redisUrl }}"
  CLIENT_URL: "{{ .Values.config.clientUrl }}"
  NODE_ENV: "{{ .Values.config.nodeEnv }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  JWT_SECRET: "{{ .Values.secrets.jwtSecret }}"
  JWT_REFRESH_SECRET: "{{ .Values.secrets.jwtRefreshSecret }}"
