import { Link } from 'react-router-dom';
import { ArrowLeft, TrendingUp, Clock, CheckCircle, Users, BarChart3, ArrowUp } from 'lucide-react';

const WEEKLY_DATA = [40, 65, 45, 80, 70, 90, 60];
const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const maxVal = Math.max(...WEEKLY_DATA);

const TEAM_STATS = [
  { name: 'Mike Johnson', meetings: 12, talkTime: '2h 14m', tasks: 8, completion: 75 },
  { name: 'Sarah Miller', meetings: 9, talkTime: '1h 48m', tasks: 6, completion: 100 },
  { name: 'Alex Chen', meetings: 11, talkTime: '2h 05m', tasks: 7, completion: 85 },
  { name: 'You (Demo User)', meetings: 14, talkTime: '3h 22m', tasks: 10, completion: 70 },
];

const METRICS = [
  { label: 'Total Meetings', value: '46', sub: 'This month', icon: <BarChart3 className="w-5 h-5" />, color: 'from-blue-500 to-blue-600', change: '+12%' },
  { label: 'Avg Duration', value: '38m', sub: 'Per meeting', icon: <Clock className="w-5 h-5" />, color: 'from-orange-500 to-orange-600', change: '-5%' },
  { label: 'Action Items', value: '84', sub: 'Generated by AI', icon: <CheckCircle className="w-5 h-5" />, color: 'from-emerald-500 to-emerald-600', change: '+23%' },
  { label: 'Completion Rate', value: '78%', sub: 'Tasks closed', icon: <TrendingUp className="w-5 h-5" />, color: 'from-purple-500 to-purple-600', change: '+8%' },
];

export default function Analytics() {
  return (
    <div className="min-h-screen bg-[#0f172a] text-slate-100 relative overflow-hidden">
      {/* Ambient glows */}
      <div className="absolute top-[-10%] left-[-5%] w-[35%] h-[35%] bg-blue-600/15 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-5%] w-[30%] h-[30%] bg-purple-600/10 rounded-full blur-[100px] pointer-events-none" />

      {/* Header */}
      <header className="h-14 md:h-16 border-b border-white/5 flex items-center justify-between px-4 md:px-8 bg-slate-900/50 backdrop-blur z-20 sticky top-0">
        <div className="flex items-center gap-3 md:gap-4">
          <Link to="/dashboard" className="p-2 text-slate-400 hover:text-white transition-colors rounded-lg hover:bg-white/5">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="text-base md:text-lg font-semibold tracking-tight">Analytics & Insights</h1>
        </div>
        <div className="flex items-center gap-1.5">
          {['7d', '30d', '90d'].map((range, i) => (
            <button key={range} className={`px-2.5 md:px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${i === 1 ? 'bg-blue-600 text-white' : 'text-slate-400 hover:text-white hover:bg-white/5'}`}>
              {range}
            </button>
          ))}
        </div>
      </header>

      <div className="max-w-6xl mx-auto p-4 md:p-8 pb-28 md:pb-8 relative z-10">

        {/* Metric Cards */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 md:gap-5 mb-6 md:mb-8">
          {METRICS.map((m) => (
            <div key={m.label} className="glass-card rounded-2xl p-3 md:p-5">
              <div className={`w-8 h-8 md:w-10 md:h-10 rounded-xl bg-gradient-to-br ${m.color} flex items-center justify-center text-white mb-3 md:mb-4 shadow-lg`}>
                {m.icon}
              </div>
              <div className="text-2xl md:text-3xl font-bold text-white mb-1">{m.value}</div>
              <div className="text-[10px] md:text-xs text-slate-400 mb-2 md:mb-3">{m.sub}</div>
              <div className={`text-[10px] md:text-xs font-semibold flex items-center gap-1 ${m.change.startsWith('+') ? 'text-emerald-400' : 'text-red-400'}`}>
                <ArrowUp className={`w-3 h-3 ${m.change.startsWith('-') ? 'rotate-180' : ''}`} />
                <span className="hidden sm:inline">{m.change} vs last month</span>
                <span className="sm:hidden">{m.change}</span>
              </div>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 md:gap-6 mb-4 md:mb-6">
          {/* Meeting Frequency Bar Chart */}
          <div className="lg:col-span-2 glass-card rounded-2xl p-6">
            <h2 className="text-base font-semibold text-white mb-1">Meeting Frequency</h2>
            <p className="text-xs text-slate-400 mb-6">Meetings per day this week</p>
            <div className="flex items-end gap-3 h-40">
              {WEEKLY_DATA.map((val, i) => (
                <div key={i} className="flex-1 flex flex-col items-center gap-2">
                  <div
                    className="w-full rounded-t-xl transition-all duration-700 relative group"
                    style={{
                      height: `${(val / maxVal) * 100}%`,
                      background: i === 4 ? 'linear-gradient(to top, #2563eb, #3b82f6)' : 'rgba(255,255,255,0.07)'
                    }}
                  >
                    <div className="absolute -top-7 left-1/2 -translate-x-1/2 text-xs font-semibold text-white opacity-0 group-hover:opacity-100 transition-opacity bg-slate-700 px-2 py-0.5 rounded">
                      {val}
                    </div>
                  </div>
                  <span className="text-[10px] text-slate-500">{DAYS[i]}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Task Completion Donut */}
          <div className="glass-card rounded-2xl p-6 flex flex-col">
            <h2 className="text-base font-semibold text-white mb-1">Task Completion</h2>
            <p className="text-xs text-slate-400 mb-6">This sprint</p>
            <div className="flex-1 flex items-center justify-center">
              <div className="relative w-32 h-32">
                <svg viewBox="0 0 36 36" className="w-full h-full -rotate-90">
                  <circle cx="18" cy="18" r="15.9" fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="3" />
                  <circle
                    cx="18" cy="18" r="15.9" fill="none"
                    stroke="url(#grad)" strokeWidth="3"
                    strokeDasharray="78 22" strokeLinecap="round"
                  />
                  <defs>
                    <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="0%">
                      <stop offset="0%" stopColor="#3b82f6" />
                      <stop offset="100%" stopColor="#8b5cf6" />
                    </linearGradient>
                  </defs>
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <span className="text-2xl font-bold text-white">78%</span>
                  <span className="text-[10px] text-slate-400">done</span>
                </div>
              </div>
            </div>
            <div className="mt-4 space-y-2">
              {[{ label: 'Done', count: 22, color: 'bg-blue-500' }, { label: 'In Progress', count: 8, color: 'bg-purple-500' }, { label: 'Backlog', count: 6, color: 'bg-slate-600' }].map(s => (
                <div key={s.label} className="flex items-center gap-2 text-xs">
                  <div className={`w-2 h-2 rounded-full ${s.color}`} />
                  <span className="text-slate-400 flex-1">{s.label}</span>
                  <span className="text-white font-medium">{s.count}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Team Performance - cards on mobile, table on desktop */}
        <div className="glass-card rounded-2xl overflow-hidden">
          <div className="px-4 md:px-6 py-4 border-b border-white/5 flex items-center gap-2">
            <Users className="w-5 h-5 text-blue-400" />
            <h2 className="font-semibold text-white text-base">Team Performance</h2>
          </div>

          {/* Mobile: Card List */}
          <div className="md:hidden divide-y divide-white/5">
            {TEAM_STATS.map((member) => (
              <div key={member.name} className="px-4 py-4">
                <div className="flex items-center gap-3 mb-3">
                  <div className="w-8 h-8 rounded-full bg-gradient-to-br from-blue-500 to-purple-500 flex items-center justify-center text-xs font-bold flex-shrink-0">
                    {member.name[0]}
                  </div>
                  <span className="text-sm font-medium text-white">{member.name}</span>
                </div>
                <div className="grid grid-cols-3 gap-2 text-center mb-3">
                  <div><p className="text-xs text-slate-500 mb-0.5">Meetings</p><p className="text-sm font-semibold text-white">{member.meetings}</p></div>
                  <div><p className="text-xs text-slate-500 mb-0.5">Talk Time</p><p className="text-sm font-semibold text-white">{member.talkTime}</p></div>
                  <div><p className="text-xs text-slate-500 mb-0.5">Tasks</p><p className="text-sm font-semibold text-white">{member.tasks}</p></div>
                </div>
                <div className="flex items-center gap-3">
                  <div className="flex-1 h-1.5 bg-white/10 rounded-full overflow-hidden">
                    <div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-purple-500" style={{ width: `${member.completion}%` }} />
                  </div>
                  <span className="text-xs text-slate-400">{member.completion}%</span>
                </div>
              </div>
            ))}
          </div>

          {/* Desktop: Table */}
          <div className="hidden md:block overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="text-[11px] text-slate-500 uppercase tracking-wider border-b border-white/5">
                  <th className="text-left px-6 py-3">Member</th>
                  <th className="text-center px-4 py-3">Meetings</th>
                  <th className="text-center px-4 py-3">Talk Time</th>
                  <th className="text-center px-4 py-3">Tasks</th>
                  <th className="text-left px-6 py-3">Completion</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/[0.04]">
                {TEAM_STATS.map((member) => (
                  <tr key={member.name} className="hover:bg-white/[0.02] transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-blue-500 to-purple-500 flex items-center justify-center text-xs font-bold">
                          {member.name[0]}
                        </div>
                        <span className="text-sm font-medium text-white">{member.name}</span>
                      </div>
                    </td>
                    <td className="px-4 py-4 text-center"><span className="text-sm text-slate-300 font-medium">{member.meetings}</span></td>
                    <td className="px-4 py-4 text-center"><span className="text-sm text-slate-300 font-medium">{member.talkTime}</span></td>
                    <td className="px-4 py-4 text-center"><span className="text-sm text-slate-300 font-medium">{member.tasks}</span></td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="flex-1 h-1.5 bg-white/10 rounded-full overflow-hidden">
                          <div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-purple-500 transition-all duration-700" style={{ width: `${member.completion}%` }} />
                        </div>
                        <span className="text-xs text-slate-400 w-8">{member.completion}%</span>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
