import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, TrendingUp, Clock, CheckCircle, Users, BarChart3, BarChart2 } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import axios from '../lib/axios';
import { InitialsAvatar, EmptyState } from '../App';

type Range = '7d' | '30d' | '90d';

// Skeleton shimmer component
const Skeleton = ({ className = '', style }: { className?: string, style?: React.CSSProperties }) => (
  <div className={`bg-slate-700/60 rounded-xl animate-pulse ${className}`} style={style} />
);

export default function Analytics() {
  const [range, setRange] = useState<Range>('7d');

  const { data: summary, isLoading: summaryLoading, isError: summaryError } = useQuery({
    queryKey: ['analytics', 'summary', range],
    queryFn: async (): Promise<any> => {
      const { data } = await axios.get(`/api/analytics/summary?range=${range}`);
      return data;
    }
  });

  const { data: teamData, isLoading: teamLoading } = useQuery({
    queryKey: ['analytics', 'team', range],
    queryFn: async (): Promise<any> => {
      const { data } = await axios.get(`/api/analytics/team?range=${range}`);
      return data;
    }
  });

  const metrics = summary ? [
    { label: 'Total Meetings', value: String(summary.metrics.totalMeetings), sub: `Last ${range}`, icon: <BarChart3 className="w-5 h-5" />, color: 'from-blue-500 to-blue-600', change: '' },
    { label: 'Avg Duration', value: `${summary.metrics.avgDurationMin}m`, sub: 'Per meeting', icon: <Clock className="w-5 h-5" />, color: 'from-orange-500 to-orange-600', change: '' },
    { label: 'Action Items', value: String(summary.metrics.totalActionItems), sub: 'Generated by AI', icon: <CheckCircle className="w-5 h-5" />, color: 'from-emerald-500 to-emerald-600', change: '' },
    { label: 'Completion Rate', value: `${summary.metrics.completionRate}%`, sub: 'Tasks closed', icon: <TrendingUp className="w-5 h-5" />, color: 'from-purple-500 to-purple-600', change: '' },
  ] : [];

  const chartData: number[] = summary?.chart?.data || [];
  const chartLabels: string[] = summary?.chart?.labels || [];
  const maxVal = chartData.length > 0 ? Math.max(...chartData, 1) : 1;

  const taskBreakdown = summary?.taskBreakdown || { done: 0, inProgress: 0, backlog: 0, todo: 0 };
  const totalTasks = taskBreakdown.done + taskBreakdown.inProgress + taskBreakdown.backlog + taskBreakdown.todo;
  const completionPercent = totalTasks > 0 ? Math.round((taskBreakdown.done / totalTasks) * 100) : 0;
  const dashArray = `${completionPercent} ${100 - completionPercent}`;

  const teamStats = teamData?.teamStats || [];
  const noData = !summaryLoading && !summaryError && summary && summary.metrics.totalMeetings === 0;

  return (
    <div className="min-h-screen bg-[#0f172a] text-slate-100 relative overflow-hidden font-sans selection:bg-blue-500/30">
      {/* Ambient glows */}
      <div className="absolute top-[-10%] left-[-5%] w-[35%] h-[35%] bg-blue-600/15 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-5%] w-[30%] h-[30%] bg-purple-600/10 rounded-full blur-[100px] pointer-events-none" />

      {/* Header */}
      <header className="h-14 md:h-16 border-b border-white/5 flex items-center justify-between px-4 md:px-8 bg-slate-900/50 backdrop-blur z-20 sticky top-0">
        <div className="flex items-center gap-3 md:gap-4">
          <Link to="/dashboard" className="p-2 text-slate-400 hover:text-white transition-colors rounded-lg hover:bg-white/5">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <h1 className="text-base md:text-lg font-semibold tracking-tight">Analytics & Insights</h1>
        </div>
        <div className="flex items-center gap-1.5">
          {(['7d', '30d', '90d'] as Range[]).map((r) => (
            <button
              key={r}
              onClick={() => setRange(r)}
              className={`px-2.5 md:px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${range === r ? 'bg-blue-600 text-white' : 'text-slate-400 hover:text-white hover:bg-white/5'}`}
            >
              {r}
            </button>
          ))}
        </div>
      </header>

      <div className="max-w-6xl mx-auto p-4 md:p-8 pb-28 md:pb-8 relative z-10">

        {noData ? (
          <div className="flex items-center justify-center min-h-[60vh]">
            <EmptyState
              icon={BarChart2}
              title="No data for this period"
              description="Hold meetings during this range to see activity, trends, and team performance."
            />
          </div>
        ) : (
          <>
            {/* Metric Cards */}
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 md:gap-5 mb-6 md:mb-8">
              {summaryLoading
                ? Array.from({ length: 4 }).map((_, i) => (
                    <div key={i} className="glass-card rounded-2xl p-3 md:p-5">
                      <Skeleton className="w-10 h-10 rounded-xl mb-4" />
                      <Skeleton className="h-8 w-16 mb-2" />
                      <Skeleton className="h-3 w-24 mb-3" />
                      <Skeleton className="h-3 w-16" />
                    </div>
                  ))
                : metrics.map((m) => (
                    <div key={m.label} className="glass-card rounded-2xl p-3 md:p-5">
                      <div className={`w-8 h-8 md:w-10 md:h-10 rounded-xl bg-gradient-to-br ${m.color} flex items-center justify-center text-white mb-3 md:mb-4 shadow-lg`}>
                        {m.icon}
                      </div>
                      <div className="text-2xl md:text-3xl font-bold text-white mb-1">{m.value}</div>
                      <div className="text-[10px] md:text-xs text-slate-400 mb-2 md:mb-3">{m.sub}</div>
                    </div>
                  ))
              }
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 md:gap-6 mb-4 md:mb-6">
              {/* Meeting Frequency Bar Chart */}
              <div className="lg:col-span-2 glass-card rounded-2xl p-6">
                <h2 className="text-base font-semibold text-white mb-1">Meeting Frequency</h2>
                <p className="text-xs text-slate-400 mb-6">Meetings per day — last {range}</p>
                {summaryLoading ? (
                  <div className="flex items-end gap-3 h-40">
                    {Array.from({ length: 7 }).map((_, i) => (
                      <div key={i} className="flex-1 flex flex-col items-center gap-2">
                        <Skeleton className={`w-full rounded-t-xl`} style={{ height: `${Math.random() * 60 + 20}%` } as any} />
                        <Skeleton className="w-6 h-3" />
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="flex items-end gap-2 md:gap-3 h-40">
                    {chartData.map((val, i) => (
                      <div key={i} className="flex-1 flex flex-col items-center gap-2">
                        <div
                          className="w-full rounded-t-xl transition-all duration-700 relative group"
                          style={{
                            height: `${Math.max((val / maxVal) * 100, val === 0 ? 2 : 0)}%`,
                            background: val > 0 ? 'linear-gradient(to top, #2563eb, #3b82f6)' : 'rgba(255,255,255,0.05)'
                          }}
                        >
                          {val > 0 && (
                            <div className="absolute -top-7 left-1/2 -translate-x-1/2 text-xs font-semibold text-white opacity-0 group-hover:opacity-100 transition-opacity bg-slate-700 px-2 py-0.5 rounded">
                              {val}
                            </div>
                          )}
                        </div>
                        <span className="text-[10px] text-slate-500">{chartLabels[i]}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Task Completion Donut */}
              <div className="glass-card rounded-2xl p-6 flex flex-col">
                <h2 className="text-base font-semibold text-white mb-1">Task Completion</h2>
                <p className="text-xs text-slate-400 mb-6">Selected period</p>
                {summaryLoading ? (
                  <div className="flex-1 flex items-center justify-center">
                    <Skeleton className="w-32 h-32 rounded-full" />
                  </div>
                ) : (
                  <div className="flex-1 flex items-center justify-center">
                    <div className="relative w-32 h-32">
                      <svg viewBox="0 0 36 36" className="w-full h-full -rotate-90">
                        <circle cx="18" cy="18" r="15.9" fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="3" />
                        <circle
                          cx="18" cy="18" r="15.9" fill="none"
                          stroke="url(#grad)" strokeWidth="3"
                          strokeDasharray={dashArray} strokeLinecap="round"
                        />
                        <defs>
                          <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="0%">
                            <stop offset="0%" stopColor="#3b82f6" />
                            <stop offset="100%" stopColor="#8b5cf6" />
                          </linearGradient>
                        </defs>
                      </svg>
                      <div className="absolute inset-0 flex flex-col items-center justify-center">
                        <span className="text-2xl font-bold text-white">{completionPercent}%</span>
                        <span className="text-[10px] text-slate-400">done</span>
                      </div>
                    </div>
                  </div>
                )}
                <div className="mt-4 space-y-2">
                  {summaryLoading ? (
                    Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-4 w-full" />)
                  ) : (
                    [
                      { label: 'Done', count: taskBreakdown.done, color: 'bg-blue-500' },
                      { label: 'In Progress', count: taskBreakdown.inProgress, color: 'bg-purple-500' },
                      { label: 'Backlog / Todo', count: taskBreakdown.backlog + taskBreakdown.todo, color: 'bg-slate-600' }
                    ].map(s => (
                      <div key={s.label} className="flex items-center gap-2 text-xs">
                        <div className={`w-2 h-2 rounded-full ${s.color}`} />
                        <span className="text-slate-400 flex-1">{s.label}</span>
                        <span className="text-white font-medium">{s.count}</span>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>

            {/* Team Performance */}
            <div className="glass-card rounded-2xl overflow-hidden">
              <div className="px-4 md:px-6 py-4 border-b border-white/5 flex items-center gap-2">
                <Users className="w-5 h-5 text-blue-400" />
                <h2 className="font-semibold text-white text-base">Team Performance</h2>
              </div>

              {teamLoading ? (
                <div className="p-6 space-y-4">
                  {Array.from({ length: 3 }).map((_, i) => (
                    <div key={i} className="flex items-center gap-4">
                      <Skeleton className="w-10 h-10 rounded-full" />
                      <div className="flex-1 space-y-2">
                        <Skeleton className="h-4 w-32" />
                        <Skeleton className="h-2 w-full" />
                      </div>
                    </div>
                  ))}
                </div>
              ) : teamStats.length === 0 ? (
                <EmptyState icon={Users} title="No team data" description="Invite team members and hold meetings to see performance here." />
              ) : (
                <>
                  {/* Mobile: Card List */}
                  <div className="md:hidden divide-y divide-white/5">
                    {teamStats.map((member: any) => (
                      <div key={member.userId} className="px-4 py-4">
                        <div className="flex items-center gap-3 mb-3">
                          <InitialsAvatar name={member.name} url={member.avatarUrl} className="w-8 h-8 text-xs" />
                          <span className="text-sm font-medium text-white">{member.name}</span>
                        </div>
                        <div className="grid grid-cols-3 gap-2 text-center mb-3">
                          <div><p className="text-xs text-slate-500 mb-0.5">Meetings</p><p className="text-sm font-semibold text-white">{member.meetings}</p></div>
                          <div><p className="text-xs text-slate-500 mb-0.5">Talk Time</p><p className="text-sm font-semibold text-white">{member.talkTime}</p></div>
                          <div><p className="text-xs text-slate-500 mb-0.5">Tasks</p><p className="text-sm font-semibold text-white">{member.tasks}</p></div>
                        </div>
                        <div className="flex items-center gap-3">
                          <div className="flex-1 h-1.5 bg-white/10 rounded-full overflow-hidden">
                            <div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-purple-500" style={{ width: `${member.completion}%` }} />
                          </div>
                          <span className="text-xs text-slate-400">{member.completion}%</span>
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Desktop: Table */}
                  <div className="hidden md:block overflow-x-auto">
                    <table className="w-full">
                      <thead>
                        <tr className="text-[11px] text-slate-500 uppercase tracking-wider border-b border-white/5">
                          <th className="text-left px-6 py-3">Member</th>
                          <th className="text-center px-4 py-3">Meetings</th>
                          <th className="text-center px-4 py-3">Talk Time</th>
                          <th className="text-center px-4 py-3">Tasks</th>
                          <th className="text-left px-6 py-3">Completion</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-white/[0.04]">
                        {teamStats.map((member: any) => (
                          <tr key={member.userId} className="hover:bg-white/[0.02] transition-colors">
                            <td className="px-6 py-4">
                              <div className="flex items-center gap-3">
                                <InitialsAvatar name={member.name} url={member.avatarUrl} className="w-8 h-8 text-xs" />
                                <span className="text-sm font-medium text-white">{member.name}</span>
                              </div>
                            </td>
                            <td className="px-4 py-4 text-center"><span className="text-sm text-slate-300 font-medium">{member.meetings}</span></td>
                            <td className="px-4 py-4 text-center"><span className="text-sm text-slate-300 font-medium">{member.talkTime}</span></td>
                            <td className="px-4 py-4 text-center"><span className="text-sm text-slate-300 font-medium">{member.tasks}</span></td>
                            <td className="px-6 py-4">
                              <div className="flex items-center gap-3">
                                <div className="flex-1 h-1.5 bg-white/10 rounded-full overflow-hidden">
                                  <div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-purple-500 transition-all duration-700" style={{ width: `${member.completion}%` }} />
                                </div>
                                <span className="text-xs text-slate-400 w-8">{member.completion}%</span>
                              </div>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </>
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
}
